name: Check Repository Health Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check for required files
        run: |
          files=("README.md" "docs/CONTRIBUTING.md" "docs/CODE_OF_CONDUCT.md" "docs/SECURITY.md" "docs/LICENSE")
          missing=false
          
          for file in "${files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: $file is missing!"
              missing=true
            fi
          done
          
          if [ "$missing" = true ]; then
            exit 1
          fi
